# This is SecretProviderClass example using service-principal for authentication with Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvstore
  namespace: api-dev
spec:
  provider: azure
  secretObjects:
  - secretName: sqlpassword
    type: Opaque
    data:
    - objectName: sqlpassword
      key: mysecret
  - secretName: sqldb
    type: Opaque
    data:
    - objectName: sqldb
      key: mysecret
  - secretName: sqluser
    type: Opaque
    data:
    - objectName: sqluser
      key: mysecret
  - secretName: sqlserver
    type: Opaque
    data:
    - objectName: sqlserver
      key: mysecret
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "kv-ohteam6"          # the name of the KeyVault
    userAssignedIdentityID: "efb4c7ae-3a4a-4615-a88b-0f08f0a07eb5"
    cloudName: ""          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: sqlpassword
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: sqldb
          objectType: secret
          objectVersion: ""
        - |
          objectName: sqluser
          objectType: secret
          objectVersion: ""
        - |
          objectName: sqlserver
          objectType: secret
          objectVersion: ""
    resourceGroup: "teamResources"
    subscriptionId: "949447fd-874d-4802-8a3e-129cab71c209"
    tenantId: "e977721b-cfeb-4c96-8397-659898f6bb60"                    # the tenant ID of the KeyVault  
