apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryatk4536.azurecr.io/tripinsights/poi:1.0
        env:
        - name: PORT
          value: "80"
        - name: WEB_PORT
          value: "80"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              key: mysecret
              name: sqluser
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysecret
              name: sqlpassword
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              key: mysecret
              name: sqlserver
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              key: mysecret
              name: sqldb
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvstore"
          nodePublishSecretRef:
            name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: poi-svc
  namespace: api-dev
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: poi
