apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryatk4536.azurecr.io/tripinsights/poi:1.0
        env:
        - name: PORT
          value: "8081"
        - name: WEB_PORT
          value: "8081"
        - name: SQL_USER
          value: "sqladminaTk4536"
        - name: SQL_PASSWORD
          value: "kF6ng8Ba1"
        - name: SQL_SERVER
          value: "sqlserveratk4536.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: poi
