apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryatk4536.azurecr.io/tripinsights/trips:1.0
        env:
        - name: PORT
          value: "80"
        - name: WEB_PORT
          value: "80"
        - name: SQL_USER
          value: "<not-set>"
        - name: SQL_PASSWORD
          value: "<not-set>"
        - name: SQL_SERVER
          value: "<not-set>"
        - name: SQL_DBNAME
          value: "<not-set>"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trips-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: trips
