apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryatk4536.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-svc.api-dev.svc.cluster.local"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile-svc.api-dev.svc.cluster.local"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-svc
  namespace: web-dev
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tripviewer
