apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryatk4536.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-svc.default.svc.cluster.local"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile-svc.default.svc.cluster.local"
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8085
    protocol: TCP
    name: http
  selector:
    app: tripviewer
