---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: trips
        image: registryatk4536.azurecr.io/tripinsights/trips:1.0
        env:
        - name: PORT
          value: "8082"
        - name: WEB_PORT
          value: "8082"
        - name: SQL_USER
          value: "sqladminaTk4536"
        - name: SQL_PASSWORD
          value: "kF6ng8Ba1"
        - name: SQL_SERVER
          value: "sqlserveratk4536.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  labels:
    app: trips
spec:
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: trips
