apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: userjava
        image: registryatk4536.azurecr.io/tripinsights/userjava:1.0
        env:
        - name: PORT
          value: "8083"
        - name: WEB_PORT
          value: "8083"
        - name: SQL_USER
          value: "<not-set>"
        - name: SQL_PASSWORD
          value: "<not-set>"
        - name: SQL_SERVER
          value: "<not-set>.database.windows.net"
        - name: SQL_DBNAME
          value: "<not-set>"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: userjava
  labels:
    app: userjava
spec:
  ports:
  - port: 80
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: userjava
