apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryatk4536.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: PORT
          value: "80"
        - name: WEB_PORT
          value: "80"
        - name: SQL_USER
          value: "<not-set>"
        - name: SQL_PASSWORD
          value: "<not-set>"
        - name: SQL_SERVER
          value: "<not-set>"
        - name: SQL_DBNAME
          value: "<not-set>"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: userprofile
